Ext.define('app.store.sms.SimSmlModel', {
    extend: 'Ext.data.Model',
    fields: [
             //tbl_sml
			{name: 'uuid', type: 'int'},
			{name: 'imsi', type: 'string'},
			{name: 'alias', type: 'string'},
			{name: 'adminStatus', type: 'int'},
			{name: 'oprStatus', type: 'int'},
			{name: 'runStatus', type: 'int'},
			{name: 'domainUuid', type: 'int'},
			{name: 'grpUuid', type: 'int'},
			{name: 'origZoneUuid', type: 'int'},
			{name: 'lastSiteUuid', type: 'int'},
			{name: 'bkpUuid', type: 'int'},
			//{name: 'bkportUuid', type: 'int'},
			{name: 'iccId', type: 'string'},
			{name: 'bindImei', type: 'string'},
			{name: 'pin1Code', type: 'string'},
			{name: 'pin2Code', type: 'string'},
			{name: 'puk1Code', type: 'string'},
			{name: 'puk2Code', type: 'string'},
			{name: 'smsc', type: 'string'},
			{name: 'operator', type: 'string'},
			{name: 'mobile', type: 'string'},
			{name: 'prepaidFee', type: 'float'},
			{name: 'totalCost', type: 'float'},
			{name: 'curBalance', type: 'float'},
			{name: 'createTime', type: 'date'},
			{name: 'lastLoadTime', type: 'date'},
			{name: 'lastBindTime', type: 'date'},
			{name: 'lastUsedTime', type: 'date'},
			{name: 'callTimeOnce', type: 'int'},
			{name: 'callTimeDay', type: 'int'},
			{name: 'callTimeMonth', type: 'int'},
			{name: 'callTimeAll', type: 'int'},
			{name: 'callInTime', type: 'int'},
			{name: 'callOutTime', type: 'int'},
			{name: 'smsCountOnce', type: 'int'},
			{name: 'smsCountDay', type: 'int'},
			{name: 'smsCountMonth', type: 'int'},
			{name: 'smsCountAll', type: 'int'},
			{name: 'smsInCount', type: 'int'},
			{name: 'smsOutCount', type: 'int'},
			{name: 'regErrorCount', type: 'int'},
			{name: 'callShortCount', type: 'int'},
			{name: 'callFailCount', type: 'int'},
			{name: 'callNormalCount', type: 'int'},
			{name: 'smsFailCount', type: 'int'},
			{name: 'deactiveReason', type: 'int'},
             //tbl_sml
             {name: 'smlUuid',type:'int'},
             {name: 'smlRecStatus',type:'int'},
             {name: 'smlDomainUuid',type:'int'},
             {name: 'userTaskType',type:'int'},
             {name: 'userTaskId',type:'int'},
             {name: 'smsIndex',type:'int'},
             {name: 'smsSn',type:'int'},
             {name: 'smlAlias',type:'string'},
             {name: 'specGrpUuid',type:'int'},
             {name: 'specSimUuid',type:'int'},
             {name: 'gwpUuid',type:'int'},
             {name: 'simUuid',type:'int'},
             {name: 'actionStatus',type:'int'},
             {name: 'actionResult',type:'int'},
             {name: 'smsDirection',type:'int'},
             {name: 'curFailRetries',type:'int'},
             {name: 'maxFailRetries',type:'int'},
             {name: 'smsNumber',type:'string'},
             {name: 'encode',type:'int'},
             {name: 'smsStatus',type:'int'},
             {name: 'smsReceipt',type:'int'},
             {name: 'smsResult',type:'int'},
             {name: 'splitCnt',type:'int'},
             {name: 'splitSuccCnt',type:'int'},
             {name: 'splitFailCnt',type:'int'},
             {name: 'smsTime',type:'date'},
             {name: 'resultTime',type:'date'},
             {name: 'receiptTime',type:'date'},
             {name: 'content',type:'string'},
             {name: 'bkpPortNoStr',type:'string'},
             {name: 'detailDesc',type:'string'},
             ]
});