Ext.define('app.store.monitor.PmdNeModel', {
        extend: 'Ext.data.Model',
        fields: [
              {name: 'uuid',type:'int'},
            {name: 'recStatus',type:'int'},
            {name: 'neUuid',type:'int'},
            {name: 'serialNo',type:'int'},
            {name:'generateTime',type:'string'},
            {name:'generateTime1',type:'date'},
            {name: 'domainUuid',type:'int'},
            {name: 'neRegFailCnt',type:'int'},
            {name: 'neRunTimelen',type:'int'},
            {name: 'sysUpTimelen',type:'int'},
            {name: 'recvPktCnt',type:'int'},
            {name: 'sendPktCnt',type:'int'},
            {name: 'recvLossCnt',type:'int'},
            {name: 'sendLossCnt',type:'int'},
            {name: 'recvTimeoutCnt',type:'int'},
            {name: 'sendTimeoutCnt',type:'int'},
            {name: 'curPingDelayMs',type:'int'},
            {name: 'minPingDelayMs',type:'int'},
            {name: 'maxPingDelayMs',type:'int'},
            {name: 'neAlias',type:'string'},
            
            {name: 'flashRdFailCount',type:'int'},
            {name: 'flashWtFailCount',type:'int'},
            {name: 'memAllocFailCount',type:'int'},
            {name: 'totalCallCount',type:'int'},
            {name: 'curCallCount',type:'int'},
            {name: 'curCpuUsage',type:'int'},
            {name: 'asr',type:'int'},
            {name: 'acd',type:'int'},
        ]
});