Ext.define('app.store.monitor.PmdSim24Model', {
        extend: 'Ext.data.Model',
        fields: [
                 {name: 'uuid',type:'int'},
                 {name: 'recStatus',type:'int'},
                 {name: 'gwpUuid',type:'int'},
                 {name: 'serialNo',type:'int'},
                 {name: 'domainUuid',type:'int'},
                 {name:'generateTime',type:'string'},
                 {name:'generateTime1',type:'date'},
                 {name: 'simSwitchCount',type:'int'},
                 {name: 'regErrorCount',type:'int'},
                 {name: 'oprErrorOnce',type:'int'},
                 {name: 'pktCountOnce',type:'int'},
                 {name: 'pktRetriesOnce',type:'int'},
                 {name: 'pktLossOnce',type:'int'},
                 {name: 'oprErrorAll',type:'int'},
                 {name: 'pktCountAll',type:'int'},
                 {name: 'pktRetriesAll',type:'int'},
                 {name: 'pktLossAll',type:'int'},
                 
                 {name: 'minSignalVal',type:'int'},
                 {name: 'curSignalVal',type:'int'},
                 {name: 'maxSignalVal',type:'int'},
                 {name: 'minBerVal',type:'int'},
                 {name: 'curBerVal',type:'int'},
                 {name: 'maxBerVal',type:'int'},
                 {name: 'minRoundDelay',type:'int'},
                 {name: 'curRoundDelay',type:'int'},
                 {name: 'maxRoundDelay',type:'int'},
                 
                 
                 {name: 'callTimeOnce',type:'int'},
                 {name: 'callTimeDay',type:'int'},
                 {name: 'callTimeMonth',type:'int'},
                 {name: 'callTimeAll',type:'int'},
                 {name: 'callInTimeAll',type:'int'},
                 {name: 'callOutTimeAll',type:'int'},
                 {name: 'callCountAll',type:'int'},
                 {name: 'callCountOnce',type:'int'},
                 {name: 'callFailCount',type:'int'},
                 {name: 'callShortCount',type:'int'},
                 {name: 'callNormalCount',type:'int'},
                 {name: 'callSuccRate',type:'string'},
                 {name: 'smsCountOnce',type:'int'},
                 {name: 'smsCountDay',type:'int'},
                 {name: 'smsCountMonth',type:'int'},
                 {name: 'smsCountAll',type:'int'},
                 {name: 'smsInCount',type:'int'},
                 {name: 'smsOutCount',type:'int'},
                 {name: 'smsFailCount',type:'int'},
                 {name: 'smsSuccRate',type:'string'},
                 {name: 'ussdCountOnce',type:'int'},
                 {name: 'ussdCountDay',type:'int'},
                 {name: 'ussdCountMonth',type:'int'},
                 {name: 'ussdCountAll',type:'int'},
                 {name: 'ussdInCount',type:'int'},
                 {name: 'ussdOutCount',type:'int'},
                 {name: 'ussdFailCount',type:'int'},
                 {name: 'ussdSuccRate',type:'int'},
                 {name: 'callCountDay',type:'int'},
                 {name: 'callCountMonth',type:'int'},
                 
                 
                 {name: 'ACD',type:'int'},
                 {name: 'ASR',type:'int'},
             ]
});