Ext.define('app.store.monitor.PmdTgMntModel', {
        extend: 'Ext.data.Model',
        fields: [
            {name: 'uuid',type:'int'},
            {name: 'recStatus',type:'int'},
            {name: 'domainUuid',type:'int'},
            {name: 'serialNo',type:'int'},
            {name:'generateTime',type:'string'}, 
            {name: 'alias',type:'string'},
            {name: 'portUuid',type:'int'},

            {name: 'value0',type:'int'},
            {name: 'value1',type:'int'},
            {name: 'value2',type:'int'},
            {name: 'value3',type:'int'},
            {name: 'value4',type:'int'},
            {name: 'value5',type:'int'},
            {name: 'value6',type:'int'},
            {name: 'value7',type:'int'},
            {name: 'value8',type:'int'},
            {name: 'value9',type:'int'},
            {name: 'value10',type:'int'},
            {name: 'value11',type:'int'},
            {name: 'value12',type:'int'},
            {name: 'value13',type:'int'},
            {name: 'value14',type:'int'},
            {name: 'value15',type:'int'},
            {name: 'value16',type:'int'},
            {name: 'value17',type:'int'},
            {name: 'value18',type:'int'},
            {name: 'value19',type:'int'},
            {name: 'value20',type:'int'},
            {name: 'value21',type:'int'},
            {name: 'value22',type:'int'},
            {name: 'value23',type:'int'},
            {name: 'value24',type:'int'},
            {name: 'value25',type:'int'},
            {name: 'value26',type:'int'},
            {name: 'value27',type:'int'},
            {name: 'value28',type:'int'},
            {name: 'value29',type:'int'},
            {name: 'value30',type:'int'},
            {name: 'value31',type:'int'},
        ]
});