Ext.define('app.store.operation.domain.group.GroupInfoModel',{
	extend: 'Ext.data.Model',
	fields: [
	         {name: 'uuid',type: 'int'},
	         {name: 'domainUuid',type: 'int'},
	         {name: 'name',type: 'string'},
	         {name: 'alias',type: 'string'},
	         {name: 'adminStatus',type: 'int'},
	         {name: 'oprStatus',type: 'int'},
	         {name: 'runStatus',type: 'int'},
	         {name: 'defaultSmsc',type: 'string'},
	         {name: 'tariffUuid',type: 'int'},
	         {name: 'zoneUuid',type: 'int'},
	         {name: 'defaultFlag',type: 'int'},
	         {name: 'cardAvailableCount',type: 'int'},
	         {name: 'callTimeAll',type: 'int'},
	         {name: 'callInTimeAll',type: 'int'},
	         {name: 'callOutTimeAll',type: 'int'},
	         {name: 'smsCountAll',type: 'int'},
	         {name: 'smsInCountAll',type: 'int'},
	         {name: 'smsOutCountAll',type: 'int'},
	         {name: 'simType',type: 'int'},
	         {name: 'resvBalanceCard',type: 'float'},
	         {name: 'minCallTimelen',type: 'int'},
	         {name: 'roamingFlag',type: 'int'},
	         {name: 'humanCallInterval',type: 'int'},
	         {name: 'humanCallDuration',type: 'int'},
	         {name: 'humanSmsInterval',type: 'int'},
	         {name: 'humanSmsCount',type: 'int'},
	         {name: 'humanRandomInterval',type: 'int'},
	         {name: 'orderType',type: 'int'},
	         {name: 'maxCallCountCard',type: 'int'},
	         {name: 'maxCallTimeOnce',type: 'int'},
	         {name: 'maxCallTimeCard',type: 'int'},
	         {name: 'maxCallTimeDay',type: 'int'},
	         {name: 'maxCallTimeMonth',type: 'int'},
	         {name: 'maxCallFeeCard',type: 'int'},
	         {name: 'maxCallFeeDay',type: 'int'},
	         {name: 'maxCallFeeMonth',type: 'int'},
	         {name: 'maxWorkTimeOnce',type: 'int'},
	         {name: 'maxIdleTimeOnce',type: 'int'},
	         {name: 'maxSmsCountCard',type: 'int'},
	         {name: 'maxSmsCountOnce',type: 'int'},
	         {name: 'maxSmsCountDay',type: 'int'},
	         {name: 'maxSmsCountMonth',type: 'int'},
	         {name: 'createTime',type: 'date'},
	         {name: 'updateTime',type: 'date'},
	         {name: 'selectCond',type: 'string'},
	         {name: 'detailDesc',type: 'string'},
	         //1030添加
	         {name: 'hbmRoleType',type: 'int'},
	         {name: 'hbmImeiFlag',type: 'int'},
	         {name: 'hbmRoamingFlag',type: 'int'},
	         {name: 'hbmAutoSmsFlag',type: 'int'},
	         {name: 'hbmAutoSmsNumber',type: 'string'},
	         {name: 'hbmAutoSmsText',type: 'string'},
	         {name: 'hbmAcdFlag',type: 'int'},
	         {name: 'hbmAcdTimeLimit',type: 'int'},
	         {name: 'hbmAcdCountLimit',type: 'int'},
	         {name: 'hbmSmsTestFlag',type: 'int'},
	         {name: 'hbmSmsCountLimit',type: 'int'},
	         {name: 'hbmSmsTestRandom',type: 'int'},
	         {name: 'hbmSmsDirection',type: 'int'},
	         {name: 'hbmSmsInterval',type: 'int'},
	         {name: 'hbmSmsTest01',type: 'string'},
	         {name: 'hbmSmsTest02',type: 'string'},
	         {name: 'hbmSmsTest03',type: 'string'},
	         {name: 'hbmSmsTest04',type: 'string'},
	         {name: 'hbmSmsTest05',type: 'string'},
	         {name: 'hbmCallTestFlag',type: 'int'},
	         {name: 'hbmCallCountLimit',type: 'int'},
	         {name: 'hbmCallTestRandom',type: 'int'},
	         {name: 'hbmCallDirection',type: 'int'},
	         {name: 'hbmCallInterval',type: 'int'},
	         {name: 'hbmCallDuration',type: 'int'},
	         {name: 'hbmDtmfTestFlag',type: 'int'},
	         {name: 'hbmDtmfTest01',type: 'string'},
	         {name: 'hbmDtmfTest02',type: 'string'},
	         {name: 'hbmDtmfTest03',type: 'string'},
	         //1116 添加
	         {name: 'maxCallDiscardFail',type: 'int'},
	         {name: 'maxCallDirection',type: 'int'},
	         {name: 'maxSmsDiscardFail',type: 'int'},
	         {name: 'maxSmsDirection',type: 'int'},
	         {name: 'maxCallCountOnce',type: 'int'},
	         {name: 'maxCallCountDay',type: 'int'},
	         {name: 'maxCallCountMonth',type: 'int'},
	         {name: 'maxCallFeeOnce',type: 'int'},
	         {name: 'minCallBillingSec',type: 'int'},
	         
	         {name: 'hbmPromNumber',type: 'string'},
	         {name: 'hbmPromSms',type: 'string'},
	         {name: 'hbmPromSuccKeys',type: 'string'},
	         {name: 'hbmPromNextGrp',type: 'int'},
	         {name: 'hbmSmsAfterReg',type: 'int'},
	         {name: 'hbmSmsNumber01',type: 'string'},
	         {name: 'hbmSmsContent01',type: 'string'},
	         {name: 'hbmSmsAfterCall',type: 'int'},
	         {name: 'hbmSmsNumber02',type: 'string'},
	         {name: 'hbmSmsContent02',type: 'string'},
	         
	         {name: 'hbmLastSmsKeys',type: 'string'},
	         {name: 'hbmLastUssdKeys',type: 'string'},
	         {name: 'hbmOfflineCleanFlag',type: 'int'},
	         //1220添加
	         {name:'modType',type:'int'},
	     	{name:'resvBalanceCard',type:'float'},
	     	{name:'callFeeRate',type:'float'},
	     	{name:'hbmTestGrpUuid',type:'int'},
	     	
	     	{name:'hbmPromMode',type:'int'},
	     	{name:'hbmModeAfterReg',type:'int'},
	     	{name:'hbmModeAfterCall',type:'int'},
	     	  
	     	{name:'hbmBalanceCheck',type:'int'},
	     	{name:'hbmBalanceMode',type:'int'},
	     	{name:'hbmBalanceNumber',type:'string'},
	     	{name:'hbmBalancePrefix',type:'string'},
	     	{name:'hbmBalanceRecharge',type:'int'},
	     	{name:'paidGrpUuid',type:'int'},
	     	   
	     	{name:'hbmSmsSwitchFlag',type:'int'},
	     	{name:'hbmCallSwitchFlag',type:'int'},

	     	{name:'maxUssdDiscardFail',type:'int'},
	     	{name:'maxUssdDirection',type:'int'},

	     	{name:'maxUssdCountCard',type:'int'},
	     	{name:'maxUssdCountOnce',type:'int'},
	     	{name:'maxUssdCountDay',type:'int'},
	     	{name:'maxUssdCountMonth',type:'int'},
	     	{name:'hbmCallToneMode',type:'int'},
	     	
	     	{name:'noBalanceLimit',type:'float'},
	     	{name:'lowBalanceLimit',type:'float'},
	     	{name:'hbmAcdDiscardFail',type:'int'},

	     	{name:'cardTotalCount',type:'int'},
	     	{name:'cardAvailableCount',type:'int'},
	     	{name:'cardIdleCount',type:'int'},
	     	//130123  add
	     	{name:'hbmSmsSpecNumber',type:'string'},
	     	{name:'hbmCallSpecNumber',type:'string'},
	     	{name:'defaultEncode',type:'int'},
	     	{name:'hbmBalanceConfirm',type:'int'},
	     	//130129 add
	     	{name:'hbmBalanceSmsFlag',type:'int'},
	     	{name:'hbmBalanceSmsNumber',type:'string'},
	     	{name:'hbmBalanceSmsPrefix',type:'string'},
	     	{name:'hbmBalanceUssdFlag',type:'int'},
	     	{name:'hbmBalanceUssdPrefix',type:'string'},

	     	{name:'hbmBalanceSmsFail',type:'string'},
	     	{name:'hbmBalanceUssdFail',type:'string'},
	     	//130201 add
	     	{name:'hbmBalancePrefix',type:'string'},
	     	{name:'hbmBalancePrefix2',type:'string'},
	     	{name:'hbmBalancePrefix3',type:'string'},

	     	{name:'hbmBalanceRetries',type:'int'},
	     	{name:'hbmBalanceFail',type:'string'},
	     	{name:'hbmBalanceFail2',type:'string'},
	     	{name:'hbmBalanceFail3',type:'string'},

	     	{name:'hbmBalanceInqFlag',type:'int'},
	     	{name:'hbmInqMode',type:'int'},
	     	{name:'hbmInqNumber',type:'string'},
	     	{name:'hbmInqContent',type:'string'},
	     	//130221 add
	     	{name:'hbmUssdQuietMonitor',type:'int'},
	     	{name:'hbmUssdQuietWaitMin',type:'int'},
	     	{name:'hbmUssdAwakeContent',type:'string'},
	     	{name:'hbmBalanceWaitMin',type:'int'},
	     	//130227 add
	     	{name:'hbmPromCfm01',type:'string'},
	     	{name:'hbmPromSms01',type:'string'},
	     	{name:'hbmPromCfm02',type:'string'},
	     	{name:'hbmPromSms02',type:'string'},
	     	{name:'hbmPromCfm03',type:'string'},
	     	{name:'hbmPromSms03',type:'string'},
	     	{name:'hbmPromFailKeys',type:'string'},
	     	{name:'hbmBalanceSucc',type:'string'},
	     	//130228 add
	     	{name:'hbmPromReqRetries',type:'int'},
	     	{name:'hbmPromWaitMin',type:'int'},
	     	{name:'hbmAcdTimeMin',type:'int'},
	     	{name:'hbmAcdTimeMax',type:'int'},
	     	//130311 add
	     	{name:'hbmMasterGrpUuid',type:'int'},
	     	{name:'hbmLearnNumber',type:'int'},
	     	{name:'hbmNumberPrefix',type:'string'},
	     	{name:'hbmPromReply01',type:'int'},
	     	{name:'hbmPromReply02',type:'int'},
	     	{name:'hbmPromReply03',type:'int'},
	     	
	     	{name:'hbmPromCfm04',type:'string'},
	     	{name:'hbmPromSms04',type:'string'},
	     	{name:'hbmPromReply04',type:'int'},
	     	
	     	{name:'hbmPromCfm05',type:'string'},
	     	{name:'hbmPromSms05',type:'string'},
	     	{name:'hbmPromReply05',type:'int'},

	     	{name:'hbmPromFailKeys2',type:'string'},
	     	{name:'hbmPromFailKeys3',type:'string'},
	     	{name:'hbmPromDayMax',type:'int'},
	     	//130313
	     	{name:'hbmOnceAfterReg',type:'int'},
	     	//130318
	     	{name:'maxPromTimeCard',type:'int'},
	     	{name:'maxRegFailCard',type:'int'},

	     	{name:'newNumberPrefix',type:'string'},
	     	//130319
	     	{name:'hbmThousandSymbol',type:'int'},
	     	{name:'hbmDecimalSymbol',type:'int'},
	     	//130411
	     	{name:'hbmInqFlag',type:'int'},
	     	{name:'hbmMaxInqCount',type:'int'},
	     	{name:'hbmInqAfterReg',type:'int'},
	     	{name:'hbmInqAfterCall',type:'int'},
	     	{name:'hbmInqAfterAcd',type:'int'},
	     	{name:'hbmInqAfterLow',type:'int'},
	     	{name:'hbmInqAfterRecharge',type:'int'},
	     	{name:'hbmInqConnect',type:'int'},
	     	{name:'hbmInqDuration',type:'int'},
	     	{name:'maxWorkSimCount',type:'int'},
	     	//130412
	     	{name:'hbmPromCfm06',type:'string'},
	     	{name:'hbmPromSms06',type:'string'},
	     	{name:'hbmPromReply06',type:'int'},
	     	//130413
	     	{name:'hbmInqTimeoutMin',type:'int'},
	     	//130513
	     	{name:'callBillingRate',type:'float'},
	     	{name:'hbmPromFlag',type:'int'},
	     	{name:'hbmPromFailKeys4',type:'string'},
	     	{name:'hbmPromFailKeys5',type:'string'},
	     	{name:'hbmPromWaitBalance',type:'int'},
	     	{name:'hbmPromInterval',type:'int'},
	     	
	     	{name:'hbmBalanceInterval',type:'int'},
	     	{name:'hbmBalancePrefix4',type:'string'},
	     	{name:'hbmBalancePrefix5',type:'string'},
	     	{name:'hbmBalanceFail4',type:'string'},
	     	{name:'hbmBalanceFail5',type:'string'},
	     	{name:'hbmBlockedCheck',type:'int'},
	     	{name:'hbmBlockedSmsFlag',type:'int'},
	     	{name:'hbmBlockedSmsNumber',type:'string'},
	     	{name:'hbmBlockedUssdFlag',type:'int'},
	     	{name:'hbmBlockedFail',type:'string'},
	     	{name:'hbmBlockedFail2',type:'string'},
	     	{name:'hbmBlockedFail3',type:'string'},
	     	{name:'maxPromTimeCall',type:'int'},
	     	{name:'maxNoBalanceWait',type:'int'},
	     	{name:'grpNotAvailableSwitch',type:'int'},
	     	{name:'lowBalanceSwitchMode',type:'int'},

	     	{name:'hbmPromSuccKeys2',type:'string'},
	     	{name:'hbmInqBlockedFlag',type:'int'},
	     	{name:'hbmInqCfm01',type:'string'},
	     	{name:'hbmInqSms01',type:'string'},
	     	{name:'hbmInqReply01',type:'int'},
	     	{name:'hbmInqCfm02',type:'string'},
	     	{name:'hbmInqSms02',type:'string'},
	     	{name:'hbmInqReply02',type:'int'},
	     	{name:'hbmInqCfm03',type:'string'},
	     	{name:'hbmInqSms03',type:'string'},
	     	{name:'hbmInqReply03',type:'int'},
	     	
	     	{name:'maxWorkTimeCard',type:'int'},
	     	
	     	{name:'hbmNextBlockedGrp',type:'int'},
	     	{name:'hbmAcdShortFlag',type:'int'},
	     	{name:'hbmAcdShortAction',type:'int'},
	     	{name:'hbmAcdFailFlag',type:'int'},
	     	{name:'hbmAcdFailCount',type:'int'},
	     	{name:'hbmAcdFailAction',type:'int'},
	     	{name:'hbmAcdAsrFlag',type:'int'},
	     	{name:'hbmAcdCallCount',type:'int'},
	     	{name:'hbmAcdAsrLimit',type:'int'},
	     	{name:'hbmAcdAsrAction',type:'int'},

	     	{name:'maxGroupTimeCard',type:'int'},

	     	{name:'minCallBilling02',type:'int'},
	     	//130814
	     	{name:'initBalanceVal',type:'float'},
	     	{name:'hbmImeiTacs',type:'string'},
	     	{name:'hbmImeiMinSn',type:'int'},
	     	{name:'hbmImeiMaxSn',type:'int'},
	     	//131219
	     	{name:'hbmInitSimFlag',type:'int'},

	     	{name:'hbmPromNextGrpName',type:'string'},
	     	{name:'hbmNextBlockedGrpName',type:'string'},

	     	{name:'defaultProfile',type:'string'},
	     	{name:'hbmNextNobalGrp',type:'int'},
	     	{name:'hbmNextNobalGrpName',type:'string'},
	     		
	     	{name:'hbmAcdGsmCode',type:'int'},
	     	{name:'hbmAcdFailWeight',type:'int'},

	     	{name:'hbmAcdGsmCode1',type:'string'},
	     	{name:'hbmAcdFailWeight1',type:'int'},
	     	{name:'hbmAcdGsmCode2',type:'string'},
	     	{name:'hbmAcdFailWeight2',type:'int'},
	     	{name:'hbmAcdFailWeight2',type:'int'},
	     	
	     	{name:'hbmAcdSmsFlag',type:'int'},
	     	{name:'hbmAcdSmsCount',type:'int'},
	     	{name:'hbmAcdSmsAction',type:'int'},
	        ]
});