Ext.define('app.store.operation.user.UserInfoModel',{
	extend: 'Ext.data.Model',
	fields: [
	         {name: 'uuid',type: 'int'},
	         {name: 'domainUuid',type: 'int'},
	         {name: 'name',type: 'string'},
	         {name: 'alias',type: 'string'},
	         {name: 'adminStatus',type: 'int'},
	         {name: 'oprStatus',type: 'int'},
	         {name: 'runStatus',type: 'int'},
	         {name: 'type',type: 'int'},
	         {name: 'passwordMd5',type: 'string'},
	         {name: 'mobile',type: 'string'},
	         {name: 'phone',type: 'string'},
	         {name: 'email',type: 'string'},
	         {name: 'address',type: 'string'},
	         {name: 'createTime',type: 'date'},
	         {name: 'lastRegTime',type: 'date'},
	         {name: 'regFailCount',type: 'int'},
	         {name: 'detailDesc',type: 'string'},
	         {name: 'pwdLength',type: 'string'},
	         {name: 'pwdLevel',type: 'string'},
	         
	         {name: 'apiEnabled',type: 'int'},
	         {name: 'maxTimeoutSec',type: 'int'},
	         {name: 'apiAuthType',type: 'int'},
	         {name: 'apiAuthPwd',type: 'string'},
	         {name: 'rsaPubKey',type: 'string'},
	         {name: 'maxReqPerMin',type: 'int'},

	         {name: 'reqCntPerMin',type: 'int'},
	         {name: 'totalReqCount',type: 'int'},
	         {name: 'totalTrapCount',type: 'int'},
	         {name: 'lastReqSn',type: 'int'},
	         {name: 'apiAuthFailCnt',type: 'int'},
	         {name: 'cliIpAddr',type: 'string'},
	         {name: 'cliPortNo',type: 'int'},
	         
	         {name: 'apiAclFlag',type: 'int'},
	         {name: 'validIpAddr',type: 'string'},
	         {name: 'validIpAddr2',type: 'string'},
	         {name: 'validIpAddr3',type: 'string'},
	         {name: 'apiTrapFlag',type: 'int'},
	         {name: 'trapIpAddr',type: 'string'},
	         {name: 'trapPortNo',type: 'int'},
	         {name: 'lastUsedTime',type: 'date'},
	         {name: 'domainName',type: 'string'},
	         {name: 'roleId',type: 'int'},
	         {name: 'roleName',type: 'string'},
	         {name: 'domainName',type: 'string'},
	         {name: 'sysName',type: 'string'},
	         ]
});