Ext.define('app.store.operation.domain.DomainPmHeadModel',{
	extend: 'Ext.data.Model',
	fields: [
	         {name: 'uuid',type: 'int'},
	         {name: 'name',type: 'string'},
	         {name: 'alias',type: 'string'},
	         {name: 'adminUserUuid',type: 'int'},
	         {name: 'defaultGrpUuid',type: 'int'},
	         {name: 'defaultVendorId',type: 'int'},
	         {name: 'sysUuid',type: 'int'},
	         {name: 'procUuid',type: 'int'},
	         {name: 'adminStatus',type: 'int'},
	         {name: 'oprStatus',type: 'int'},
	         {name: 'runStatus',type: 'int'},
	         {name: 'idleTime',type: 'int'},
	         {name: 'specSysUuid',type: 'int'},
	         {name: 'timezoneFlag',type: 'int'},
	         {name: 'ntpServer1',type: 'string'},
	         {name: 'ntpServer2',type: 'string'},
		     {name: 'localTimeZone',type: 'int'},
	         {name: 'detailDesc',type: 'string'},
	         {name: 'userName',type: 'string'},
	         {name: 'serverName',type: 'string'},

	         {name: 'idleSwitchFlag',type: 'int'},
	         {name: 'smoothSwitchFlag',type: 'int'},
	         {name: 'switchTimeout',type: 'int'},

	         {name: 'sysLockedFlag',type: 'int'},
	         {name: 'devTimeFlag',type: 'int'},
	         {name: 'timezoneFlag',type: 'int'},
	         {name: 'type',type: 'int'},
	         
	         {name: 'alarmMax',type: 'int'},
	         {name: 'pm15mMax',type: 'int'},
	         {name: 'pm15mSn',type: 'int'},
	         {name: 'pm15mCount',type: 'int'},
	         {name: 'pm24hMax',type: 'int'},
	         {name: 'pm24hSn',type: 'int'},
	         {name: 'pm24hCount',type: 'int'},
	         {name: 'pmCallMax',type: 'int'},
	         {name: 'pmSmsMax',type: 'int'},
	         {name: 'pmUssdMax',type: 'int'},
	         {name: 'snumberMax',type: 'int'},
	         {name: 'dnumberMax',type: 'int'},
	         {name: 'vendorId',type: 'int'},
	         //130227 add
	         {name: 'createTime',type: 'date'},
	         {name: 'updateTime',type: 'date'},
	         //130311 add
	         {name: 'hbmSendRetries',type: 'int'},
	         {name: 'saveSmsFail',type: 'int'},
	         {name: 'saveUssdFail',type: 'int'},
	         {name: 'saveCallFail',type: 'int'},
	         //130311 add
	         {name: 'scpTimeoutSec',type: 'int'},
	         //130412 add
	         {name: 'scpPingChannel',type: 'int'},
	         
	         {name: 'pushSmsInterval',type: 'int'},
	         {name: 'pushMailInterval',type: 'int'},
	         {name: 'pushCallInterval',type: 'int'},
	         
	         {name: 'pushSmsLevel',type: 'int'},
	         {name: 'pushCallLevel',type: 'int'},
	         {name: 'pushMailLevel',type: 'int'},
	         {name: 'pushSmsEncode',type: 'int'},
	         {name: 'pushNeUuid1',type: 'int'},
	         {name: 'pushSmsPort1',type: 'int'},
	         {name: 'pushNeUuid2',type: 'int'},
	         {name: 'pushSmsPort2',type: 'int'},
	         {name: 'pushSmsAddr',type: 'string'},
	         {name: 'pushCallAddr',type: 'string'},
	         {name: 'pushMailAddr',type: 'string'},
	         {name: 'pushSmsRetryMax',type: 'int'},
	         {name: 'pushMailRetryMax',type: 'int'},
	         {name: 'pushCallRetryMax',type: 'int'},
	         {name: 'mailRelayEnable',type: 'int'},
	         {name: 'smtpServer',type: 'string'},
	         {name: 'smtpPort',type: 'int'},
	         {name: 'startTls',type: 'int'},
	         {name: 'smtpUserName',type: 'string'},
	         {name: 'smtpPassWord',type: 'string'},
	         {name: 'mailFrom',type: 'string'},

	         {name: 'portStatsFlag',type: 'int'},
	         {name: 'simStatsFlag',type: 'int'},
	         {name: 'totalNeCount',type: 'int'},
	         {name: 'totalSimCard',type: 'int'},

	         {name: 'signType',type: 'int'},
	         {name: 'licStatus',type: 'int'},
	         {name: 'leftDays',type: 'int'},

	         {name: 'productId',type: 'int'},
	         {name: 'nodeEncryptFlag',type: 'int'},
	         {name: 'offlineCleanMode',type: 'int'},
	         {name: 'onlineNeCount',type: 'int'},
	         {name: 'onlineSimCard',type: 'int'},
	         {name: 'lastLoginTime',type: 'date'},
	         
	         {name: 'antiCallScanEnable',type: 'int'},
	         {name: 'shortCallParam',type: 'int'},
	         {name: 'longCallParam1',type: 'int'},
	         {name: 'longCallParam2',type: 'int'},
	         {name: 'longCallParam3',type: 'int'},
	         {name: 'numberExpireTime',type: 'int'},
	         
	         {name: 'callerGrayFlag',type: 'int'},
	         {name: 'calleeGrayFlag',type: 'int'},
	         {name: 'ipGrayFlag',type: 'int'},
	         {name: 'dynamicStaticsEnable',type: 'int'},
	         {name: 'blackInfectFlag',type: 'int'},
	         {name: 'dynamicCallerEnable',type: 'int'},
	         {name: 'numberValidLen',type: 'int'},
	         {name: 'failCallWeight',type: 'int'},
	        ]
});