Ext.define('app.store.operation.domain.SysDomainModel',{
	extend: 'Ext.data.Model',
	fields: [
	         {name: 'bkNum',type: 'int'},
			 {name: 'gwNum',type: 'int'},
			 {name: 'deviceNum',type: 'int'},
	         {name: 'uuid',type: 'int'},
	         {name: 'name',type: 'string'},
	         {name: 'alias',type: 'string'},
	         {name: 'specCloudUuid',type: 'int'},
	         {name: 'cloudUuid',type: 'int'},
	         {name: 'cloudName',type: 'string'},
	         {name: 'specCloudName',type: 'string'},
	         {name: 'sysUuid',type: 'int'},
	         {name: 'serverName',type: 'string'},
	         {name: 'specSysUuid',type: 'int'},
	         {name: 'specServerName',type: 'string'},
	         {name: 'detailDesc',type: 'string'},
	         {name: 'adminStatus',type: 'int'},
	         {name: 'oprStatus',type: 'int'},
	         {name: 'runStatus',type: 'int'},
	         {name: 'vendorId',type: 'int'},
	         {name: 'type',type: 'int'},
	         {name: 'sysLockedFlag',type: 'int'},
	         {name: 'alarmMax',type: 'int'},
	         {name: 'pm15mMax',type: 'int'},
	         {name: 'pm24hMax',type: 'int'},
	         {name: 'pmCallMax',type: 'int'},
	         {name: 'pmSmsMax',type: 'int'},
	         {name: 'pmUssdMax',type: 'int'},
	         {name: 'logUserMax',type: 'int'},
	         {name: 'nodeGrpUuid',type: 'int'},
	         {name: 'nodeGrpName',type: 'string'},

	         {name: 'createTime',type: 'date'},
	         {name: 'updateTime',type: 'date'},

	         {name: 'productId',type: 'int'},
	         {name: 'totalNeCount',type: 'int'},
	         {name: 'totalSimCard',type: 'int'},
	         {name: 'nodeEncryptFlag',type: 'int'},
	         {name: 'offlineCleanMode',type: 'int'},
	         {name: 'onlineNeCount',type: 'int'},
	         {name: 'onlineSimCard',type: 'int'},
	         {name: 'lastLoginTime',type: 'date'},
	         {name: 'snumberMax',type: 'int'},
	         {name: 'dnumberMax',type: 'int'},
	        ]
});
console.log("load domain info model");