define(function (){
	return {
		workStation:"Work Station",
		devManage:"Device Manage",
		serverManage:"Server Manage",
		serviceManage:"Service Manage",
		userManage:"User Manage",
		payManage:"Pay",
		versionStore:"Version Store",
		logout:"Logout",
		devModelStore:"Device Model Store",
		devCalc:"Device Statistic",
		devList:"Device List",
		confList:"Config Store",
		callCalc:"Call Statistic",
		perCalc:"Perform Statistic",
		alarmCalc:"Alarm Statistic",
		alarmLog:"Alarm Log",
		runLog:"Run Log",
		onlineStatus:"Online Status",
		usageRate:"Usage Rate",
		portNotValid:'Invalid port,input should between 0-65535',
		hostNotValid:'Invalid host',
		alarm:"Alarm",		
		name:"Name",
		model:"Model",
		userList:"User List",
		roleList:"Role List",
		version:"Version",		
		status:"Status",
		regTime:"Register Time",
		site:"Site",
		zone:"Zone",
		domain:"Domain",
		dev:"Device",
		devs:"Devices",
		desc:"Description",
		sn:"SN",
		alias:"Alias",
		alarmApiHost:'Host',
		alarmApiPort:'Port',
		alarmApiSwitch:'Alarm Api Switch',
		alarmApiPath:'Path',
		alarmApi:'Alarm Api',
		productName:"Product Name",
		allClassify:"All Classification",
		devLocation:"Device Location",
		unknownDev:"Unknown Dev",
		unknownDevList:"Unknown Device List",
		added:"Added",
		notAdd:"Not_Add",
		unknown:"Unknown",
		devStatus:"Device Status",
		devType:"Device Type",
		devType_1:"MTG",
		devType_2:"DAG",
		online:"Online",
		offline:"Offline",
		init:"Init",
		commFail:"Comm_Fail",
		active:"Active",
		busy:"Busy",
		open:"Open",
		changePwd:"Change Password",
		close:"Close",
		disable:"Disable",
		invalidParam:"Invalid Param",
		mtg:"MTG",
		dag:"DAG",
		uc:"UC",
		dag80:"Hi_core",
		reportSwitch:'Report Switch',
		chipType:'Chip Type',
		devReport:'Device Report',
		total:"Total",
		devs:"Devices",
		multiSel:"Multi",
		homePage:"Home",
		cancel:"Cancel",
		confirm:"OK",
		more:"More",
		idle:"Idle",
		transToOld:"Trans to Old",
		adminStatus_0:'NULL',
		adminStatus_1:'ENABLED',
		adminStatus_2:'DISABLED',	
		adminStatus_3:'MAINTENANCE',	
		adminStatus_4:'DEMO',	
		adminStatus_5:'LOCKED',	
		adminStatus_6:'NO_BALANCE',	
		runStatus_0:'NOT_REG',
		runStatus_1:'INIT',
		runStatus_2:'NEED_AUTH',
		runStatus_3:'ACTIVE',
		runStatus_4:'FAULT',
		runStatus_5:'EMPTY',
		runStatus_6:'COMM_FAIL',
		runStatus_7:'MISMATCH',
		runStatus_8:'FAC_FAULT',
		runStatus_9:'DISABLED',
		runStatus_10:'IDLE',
		runStatus_11:'BUSY',
		runStatus_12:'LOCKED',
		runStatus_13:'ELEGANT_STOP',
		runStatus_14:'TESTING',
		runStatus_15:'READY',
		runStatus_16:'STOPPED',
		runStatus_17:'NO_BALANCE',
		runStatus_18:'OFFLINE',
		runStatus_19:'REBOOT',
		runStatus_20:'LOW_BALANCE',
		runStatus_21:'BLOCKED',
		runStatus_22:'EXPIRED',
		oprStatus_0:'NULL',  
		oprStatus_1:'NORMAL',
		oprStatus_2:'OUTAGE',
		oprStatus_3:'BUTT',
		oprStatus_4:'BUTT',
		workStatus_0:'NO_SIM',
		workStatus_1:'READY',
		workStatus_2:'WORKING',
		workStatus_3:'DISABLED',
		devModelList:"Device Model List",
		upgradeType_0:'DISABLED',
		upgradeType_1:'TO_TARGET_VERSION',
		upgradeType_2:'TO_NEWEST_BELTA',
		upgradeType_3:'TO_NEWEST_OFFICIAL',
		alarmLevel_0:"EMERG",
		alarmLevel_1:"ALERT",
		alarmLevel_2:"CRIT",
		alarmLevel_3:"ERR",
		alarmLevel_4:"WARNING",
		alarmLevel_5:"NOTICE",
		alarmLevel_6:"INFO",
		alarmLevel_7:"DEBUG",
		alarmLevel_8:"Disable",
		cfgType_1:"Manual",
		cfgType_2:"Auto",
	    dmNumAction_0:'NULL',
	    dmNumAction_1:'DISABLE_CALL',
	    dmNumAction_2:'DISABLE_PASS',
	    dmNumAction_3:'DIABLE_CALL_AND_PASS',
	    dmNumAction_4:'RECORD',
	    dmNumAction_5:'CALL_FREQ',
	    chipType_80:'MIPS-MT7621',
	    chipType_81:'ARM-S805',
	    chipType_82:'ARM-R58',
	    faxCnt:'Fax Cnt',
	    alarmCnt:'Alarm Cnt',
	    alertAlarmCnt:'Alert Alarm Cnt',
	    resetCnt:'Reset Cnt',
	    alertAlarmAvgTime:'Alert Alarm<br>Avg Time',	 
	    role_1:'Calling',
	    role_2:'Called',
		primaryStatus_0:'NA',
		primaryStatus_1:'UNCONFIG',
		primaryStatus_2:'SUCCESS',
		primaryStatus_3:'FAIL',
		sipRegFlag_0:'NA',
		sipRegFlag_1:"NO",
		sipRegFlag_2:"YES",
		sipCallMode_0:'NA',
		sipCallMode_1:"ACCESS",
		sipCallMode_2:"PEER",
		priWorkStatus_0:'NA',
		priWorkStatus_1:"OFF",
		priWorkStatus_2:"ON",
		ss7Type_0:'NA',
		ss7Type_1:"TUP",
		ss7Type_2:"ISUP",
		ss7Mode_0:'NA',
		ss7Mode_1:"MASTER",
		ss7Mode_2:"SLAVE",
		ss7WorkStatus_0:'NA',
		ss7WorkStatus_1:"OFF",
		ss7WorkStatus_2:"ON",
		dspPcmLaw_0:'NA',
		dspPcmLaw_1:"PCM_LAW_A",
		dspPcmLaw_2:"PCM_LAW_U",
		dspWorkStatus_0:'NA',
		dspWorkStatus_1:"INIT",
		dspWorkStatus_2:"IDLE",
		dspWorkStatus_3:"OVERLOAD",
		ethWorkState_0:'NA',
		ethWorkState_1:"DOWN",
		ethWorkState_2:"HALF/10M",
		ethWorkState_3:"HALF/100M",
		ethWorkState_4:"HALF/1000M",
		ethWorkState_5:"FULL/10M",
		ethWorkState_6:"FULL/100M",
		ethWorkState_7:"FULL/1000M",
		ethSpeed_0:'NA',
		ethSpeed_1:"10M",
		ethSpeed_2:"100M",
		ethSpeed_3:"1000M",
		ethMode_0:'NA',
		ethMode_1:"AUTO NEG",
		ethMode_2:"MANUAL",
		ntpStatus_0:'NA',
		ntpStatus_1:'SYN',
		ntpStatus_2:'NOSYN',
		ntpStatus_16:'SYN',
		ntpStatus_17:'DISABLE',
		ntpStatus_18:'SUCCESS',
		ntpStatus_19:'FAIL',
		autoRebootFlag_0:'NA',
		autoRebootFlag_1:"TRUE",
		autoRebootFlag_2:"FLASE",
		timeChipStatus_0:'NA',
		timeChipStatus_1:"IDLE",
		timeChipStatus_2:"FAIL",
		switchChipStatus_0:'NA',
		switchChipStatus_1:"IDLE",
		switchChipStatus_2:"FAIL",
		portType_9217:'GWP',
		portType_9218:"BKP",
		portType_9219:"AGP",
		portType_9220:"E1",
		portType_9221:"ETH",
		portType_9222:"LAN",
		portType_9473:"DSP",
		portType_9474:"SS7",
		portType_9475:"PRI",
		portType_9476:"SIP",
		portType_9477:"H323",
		portType_9478:"R2",
		tgpPcmMode_0:'NA',
		tgpPcmMode_1:'A LAW',
		tgpPcmMode_2:"U LAW",
		tgpFrameMode_0:'NA',
		tgpFrameMode_1:'CRC4',
		tgpFrameMode_2:"CRC4 ITU",
		tgpFrameMode_3:"DF",
		tgpFrameMode_4:"F12/SF",
		tgpFrameMode_5:"F4/FT",
		tgpFrameMode_6:"F24/ESF",
		tgpFrameMode_7:"F72/SLC96",
		tgpLineCode_0:'NA',
		tgpLineCode_1:'HDB3',
		tgpLineCode_2:"AMI",
		tgpLineCode_3:"CMI",
		tgpLineCode_4:"NRZ",
		tgpLineCode_5:"B8ZS",
		tgpLineBuiltOut_0:'NA',	
		tgpLineBuiltOut_1:'SHORT HAUL',
		tgpLineBuiltOut_2:"LONG HAUL",
		tgpClockSrc_0:'NA',
		tgpClockSrc_1:'LOCAL',
		tgpClockSrc_2:"REMOTE",
		priProto_0:'NA',
		priProto_1:'ISDN',
		priProto_2:"QSIG",
		priSwside_0:'NA',
		priSwside_1:'USER SIDE',
		priSwside_2:"NETWORK SIDE",
		priAlertIndi_0:'NA',
		priAlertIndi_1:'ALERTING',
		priAlertIndi_2:"PROGRESS",
		sipTransProto_0:'NA',
		sipTransProto_1:'UDP',
		sipTransProto_2:"TCP",
		sipAuthType_0:'NA',
		sipAuthType_1:'PASSWORD',
		sipAuthType_2:"IP",
		sipSipT_0:'NA',
		sipSipT_1:'YES',
		sipSipT_2:"NO",
		sipLinkStatus_0:'NA',
		sipLinkStatus_1:'OFF',
		sipLinkStatus_2:"ON",
		sipDetectTrunk_0:'NA',
		sipDetectTrunk_1:'YES',
		sipDetectTrunk_2:"NO",
		ss7Proto_0:'NA',
		ss7Proto_1:'ITU',
		ss7Proto_2:"ANSI",
		ss7Proto_3:"ITU-CHINA",
		ss7NetIndi_0:'NA',
		ss7NetIndi_1:'International Network',
		ss7NetIndi_2:"International Spare",
		ss7NetIndi_3:"National Network",
		ss7NetIndi_4:"National Spare",
		ss7LinkStatus_0:'NA',
		ss7LinkStatus_1:'OFF',
		ss7LinkStatus_2:"ON",
		ss7SendSltm_0:'NA',
		ss7SendSltm_1:'ENABLED',
		ss7SendSltm_2:"DISABLED",
		ss7SendSltm_3:"NA",
		lastFail_0:'NA',
		lastFail_1:'MAX_SESSION',
		lastFail_2:'NOT_FIND_RT',
		lastFail_3:'CRT_RTP_FAIL',
		lastFail_4:'MODIFY_RTP_FAIL',
		lastFail_5:'SERVER_REJECT',
		tgpWorkState_0:"NA",
		tgpWorkState_1:"READY",
		tgpWorkState_2:"ESTABLISHING",
		tgpWorkState_3:"FAULT",
		tgpWorkState_4:"BLOCK",
		tgpWorkState_5:"BLOCK",
		tgpWorkState_6:"BLOCK",
		tgpModType_0:"NA",
		tgpModType_1:"E1",
		tgpModType_2:"T1",
		signalType_0:"UNUSED",
		signalType_1:"Q931",
		signalType_2:"SS7_TUP",
		signalType_3:"SS7_ISUP",
		signalType_4:"R2",
		userType_0:'Super User',
		userType_1:'Administrator',
		userType_2:'Normal User',
		userType_3:'Message User',
		enable:"Enable",
		disable:"Diable",
		vendor_0:'NULL',
		vendor_1:'UCSPEED',
		vendor_2:'DINSTAR',
		vendor_3:'CHANGYOU',
		vendor_12:'IRL',
		vendor_13:'SHENGHE',
		vendor_15:'HANGZHOU_ZHONGFANG',
		vendor_18:'VERDOR_18',
		vendor_25:'JINGLUN',
		vendor_26:'VOS_ELECTRONICS',
		vendor_27:'WILDIX',
		vendor_31:'ANZHENG',
		vendor_32:'DISCOVERY',
		vendor_36:'VERDOR_36',
		vendor_40:'HANDPHONE',
		vendor_41:'SOLUCIONES',
		vendor_48:'VOIPOINT',
		vendor_50:'VERDOR_50',
		vendor_52:'SAGEM',
		vendor_60:'DLINK',
		vendor_80:'PARADOXES',
		vendor_88:'INTACT',
		vendor_90:'ECYB',
		vendor_91:'VERDOR_91',
		vendor_99:'UCSPEED',
		vendor_101:'UCSPEED_DM',
		vendor_102:'DINSTAR_DM',
		agpWorkState_0:"NA",
		agpWorkState_1:"FAULT",
		agpWorkState_2:"DISABLE",
		agpWorkState_3:"ONHOOK",
		agpWorkState_4:"OFFHOOK",
		agpWorkState_5:"OFFLINE",
		agpWorkMode_0:"NA",
		agpWorkMode_1:"FXS",
		agpWorkMode_2:"FXO",
		sipServer:'SIP Server',
		numAuth:'Number Auth',
		freqControl:'Freq Control',
		disableCall:'Disable Call',
		disablePass:'Disable Pass',
		record:'Record',
		addRole:'Add a Role',
		welcomeUse:'Welcome to use',
		plSelUser:'Please select user',
		plSelOperate:'Please select operate',
		plSelDomain:'Please select domain',
		plSelDomain_1:'Select Domain',
		plSelServUnderDomain:'please select node under domain',
		canNotDelDefault:'Default node can not be deleted',
		calcDayCnt:'Calc Day Cnt',
		view:'View',
		refresh:'Refresh',
		addr:'Address',
		curStatus:'Cur Status',
		hisCalc:'History',
		pcs:'pcs',
		drServer:'record server',
		dcServer:'diable call server',
		autoRef:'Auto Refresh',
		secs:'secs',
		add:'Add',
		memUsage:'Mem Usage',
		diskUsage:'Disk Usage',
		cpuUsage:'CPU Usage',
		sureToDel:'Are you sure to delete',
		sureToRestorePwd:'Are you sure to restore password',
		curSessionCnt:'Cur Sessions',
		fileCnt:'Files',
		option:'Option',
		remoteWeb:'Remote Web',
		drpRemoteWeb:'DRP Remote Web',
		del:'Delete',
		time:'Time',
		sessionCnt:'Sessions',
		diskUsed:'Disk Used',
		filter:'Filter',
		fromTime:'From Time',
		toTime:'To Time',
		expt:'Export',
		content:'Content',
		noRecords:'No Records',
		alarmName:'Alarm Name',
		alarmLevel:'Alarm Level',
		sn:'SN',
		exportFail:'Export Fail',
		exportSucc:'Export Success',
		maxProcessTime:'Max Proc Time',
		avgProcessTime:'Avg Proc Time',
		totalProcess:'Total Process',
		processCnt:'Proc Cnt',
		processTime:'Proc Time',
		curDealCnt:'Cur Deal Cnt',
		curPendingCnt:'Cur Pending Cnt',
		curDealStatus_1:'DISABLE_CALL_CNT',
		curDealStatus_2:'DISABLE_PASS_CNT',
		curDealStatus_3:'DISABLE_CALL_AND_PASS_CNT',
		curDealStatus_4:'RECORD_CNT',
		devAlias:'Dev Alias',
		priSipAddr:'Pri Sip Addr',
		priSipPort:'Pri Sip Port',
		secSipAddr:'Sec Sip Addr',
		secSipPort:'Sec Sip Port',
		sipServer:'Sip Server',
		productSn:'Device SN',
		runStatus:'Run Status',
		sipsrvLockFlag:'Sip Srv Lock Flag',
		set:'Set',
		impt:'Import',
		num:'Number',
		createTime:'Create Time',
		globalControl:'Global Control',
		whiteNum:'White Num',
		blackNum:'Black Num',
		callerFreqControl:'Calling Freq',
		calleeFreqControl:'Called Freq',
		save:'Save',
		setSucc:'Set Success',
		setSucc_1:'Set successfully,device will do restore,it will take several minutes',
		setFail:'Set Fail',
		freqSwitch:'Freq Switch',
		period:'Period',
		callMaxNum:'Call Max Num',
		nullNotChange:'If 0 or null,it will not change',
		mins:'mins',
		direction:'Direction',
		addServer:'Add Server',
		commit:'Commit',
		addSucc:'Add Success',
		addFail:'Add Fail',
		commitSucc:'Commit Success',
		commitFail:'Commit Fail',
		cloud:'Cloud',
		ipCanNotEmpty:'IP can not be empty',
		ipNotValid:'IP is not valid',
		ipIsExist:'IP is exist',
		caller:'Calling',
		callee:'Called',
		ifEmptyUseGlobal:'If emtpy,it will use global value',
		youNotSel:'No selections',
		onlyOnePermit:'Allow only one selection',
		plSelOnlineDev:'Please select online dev',
		plSelFile:'Please select file',
		importingPlWait:'Importing,please wait',
		importSucc:'Import Success',
		importFail:'Import Fail',
		exportingPlWait:'Exporting,please wait',
		delSucc:'Delete Success',
		delFail:'Delete Fail',
		sel:'Select',
		plSelXml:'Please select xml file',
		plSelXls:'Please select xls(excel 2003) file',
		phone:'Phone',
		email:'Email',
		user:'User',
		resetPwd:'Reset Password',
		setPwd:'Set Password',
		password:'Password',
		mobile:'Mobile',
		role:'Role',
		productNameCanNotEmpty:'Product name can not be empty',
		userCanNotEmpty:'User can not be empty',
		pwdCantNotEmpty:'Password can not be empty',
		siteCantNotEmpty:'Site can not be empty',
		emailCanNotEmpty:'Email can not be empty',
		emailNotValid:'Email is not valid',
		userIsUse:'User is exist',
		superAdminCanNotDel:'Can not delete super admin',
		canNotDelYourself:'Can not del yourself',
		needOneDomainAdmin:'Domain needs at least one domain admin',
		maxTimeout:'Max Timeout',
		authType:'Auth Type',
		authPwd:'Auth Password',
		maxReqTime:'Max Req Time',
		ip1:'IP1',
		ip2:'IP2',
		ip3:'IP3',
		orderItemStatus_0:'NOT_UPDATE',
		orderItemStatus_1:'UPDATED',
		pushSetting:'Push Setting',
		pushIp:'Push IP',
		pushPort:'Push Port',
		rightSpecialFinance:'Finance',
		rightModuleConfiguration:'Config',
		rightModulePerformance:'Perform',
		rightModuleLog:'Log',
		rightModuleVersion:'Version Info',
		rightModuleProvision:'Provision',
		rightModuleSystem:'System',
		rightModuleLicense:'License',
		rightModulePrivilege:'Privilege',
		rightModuleBatch:'Batch',
		rightSuperRead:'Super Read',
		rightSuperEdit:'Super Edit',
		rightSuperAction:'Super Action',
		rightDomainRead:'Domain Read',
		rightDomainEdit:'Domain Edit',
		rightDomainAction:'Domain Action',
		rightDeviceAction:'Device Action',
		rightSimAction:'SIM Action',
		rightApiAction:'API Action',
		devAlarm:'Device Alarm',
		serverAlarm:'Server Alarm',
		serviceAlarm:'Service Alarm',
		callAlarm:'Call Alarm',
		goToPrevView:'Go to prev view',
		ownDomain:'Location Domain',
		ownZone:'Location Zone',
		ownSite:'Location Site',
		groupByDomain:'Group by Domain',
		groupByZone:'Group by Zone',
		groupBySite:'Group by Site',
		refreshingWait:'Refreshing,please wait',
		versionDistribution:'Version Distribution',
		cnt:'Count',
		devCnt:'Dev',
		dagCnt:'Dag',
		mtgCnt:'Mtg',
		onlineDevCnt:'Online Dev',
		onlineMtgCnt:'Online Mtg',
		onlineDagCnt:'Online Dag',
		devFaultCnt:'Fault',
		upgradingCnt:'Upgrading',
		dboEnableCnt:'DBO Enable',
		batchingCnt:'Batching',
		portCnt:'Port',
		fxsCnt:'FXS',
		fxoCnt:'FXO',
		regSuccPortCnt:'Reg Success',
		regFailPortCnt:'Reg Fail',
		noAccountPortCnt:'No Account',
		e1Cnt:'E1',
		enableE1Cnt:'E1 Enable',
		sipCnt:'SIP',
		priCnt:'PRI',
		ss7Cnt:'SS7',
		devIsNotOnline:'Device is not online',
		apply:'Apply',
		upgrade:'Upgrade',
		restart:'Restart',
		restorePwd:'Restore Password',
		resetPort:'Reset Port',
		devName:'Dev Name',
		lastRegTime:'Last Reg Time',
		dboSwitch:'DBO Switch',
		cfgBackup:'CFG Backup',
		cfgRestore:'CFG Restore',
		detail:'Detail',
		e1WorkStatusDesc:'E1 Work Status Description',
		portType:'Port Type',
		devType:'Device Type',
		curVersion:'Cur Version',
		enableCnt:'Enable Count',
		e1WorkStatus_1:'NOT_USE',
		e1WorkStatus_2:'ACTIVE',
		e1WorkStatus_3:'LOS Alarm',
		e1WorkStatus_4:'RAI Alarm',
		e1WorkStatus_5:'AIS Alarm',
		e1WorkStatus_6:'ISDN/SS7 Alarm',
		mtgThumbnail:'MTG Thumbnail',
		callThumbnail:'Call Thumbnail',
		settingWait:'Setting,please wait',
		devWillRestartContinue:'Device will restart,continue',
		type:'Type',
		callCnt:'Call Count',
		callTime:'Call Time',
		callSuccCnt:'Call Succ Count',
		callFailCnt:'Call Fail Count',
		maxCpuRate:'Max Cpu Rate',
		cpuHighTimeRate:'Cpu High<br>Time Rate',
		acd:'ACD',
		asr:'ASR',
		lastHour:'Last Hour',
		lastDay:'Last Day',
		lastWeek:'Last Week',
		lastMonth:'Last Month',
		regFailCnt:'Register Fail Count',
		runTimeAfterReg:'Run Time After Register',
		recvLostRate:'Recv Lost Rate',
		sendLostRate:'Send Lost Rate',
		curPingDelay:'Cur Ping Delay',
		ms:'ms',
		maxPingDelay:'Max Ping Delay',
		flashReadFailCnt:'Flash Read Fail Cnt',
		flashWriteFailCnt:'Flash Write Fail Cnt',
		memAllocFailCnt:'Mem Alloc Fail Cnt',
		neRunTime:'Device Run Time',
		curCpuUsage:'Cur Cpu Usage',
		and:'And',
		lostRate:'Lost Rate',
		pingDelay:'Ping Delay',
		memAndFlash:'Mem And Flash',
		neReg_1:'Device Run Time After Reg',// ne reg fail cnt and ne run time
											// after reg
		portList:'Port List',
		basicInfo:'Basic Info',
		adminStatus:'Admin Status',
		detailInfo:'Detail Info',
		vendor:'Vendor',
		regPwd:'Register Password',
		show:'Show',
		hide:'Hide',
		outIp:'Out IP',
		softBuiltTime:'Soft Built Time',
		detailVer:'Detail Version',
		lastUpgradeTime:'Last Upgrade Time',
		lastUpgradeResult:'Last Upgrade Result',
		perInfo:'Performance Info',
		upgradeStatus:'Upgrade Status',
		targetVer:'Target Version',
		upgradeSetting:'Upgrade Setting',
		toTargetVer:'to Target Version',
		upgradeInfo:'Upgrade Info',
		avgCpuUsage:'Average Cpu Usage',
		memUsage:'Memory Usage',
		applySucc:'Apply Success',
		applyFail:'Apply Fail',
		applyingWait:'Applying Wait',
		plSelDomainOrZoneOrSite:'Please Select domain or zone or site',
		productSnCanNotEmpty:'Product sn can not be empty',
		productSn_1:'Device sn format:XXXX-XXXX-XXXX-XXXX,X is 0-9 or a-f',
		devNameIsExist:'Device name is exist',
		productSnIsExist:'Device sn is Exist',
		devNameCanNotEmpty:'Device name can not be empty',
		sureToRestart:'Are you sure to restart',
		plSelDevInSameDomain:'Please select device in the same domain',
		plSelDevNotAdd:'Please select device not added',
		devIsNotInDomain:'Device is not in domain',
		mtgNotSupportRemote:'MTG not support remote web',
		gettingDevRouteWait:'Getting dev route,please wait',
		gettingSucc:'Getting Success',
		gettingFail:'Getting Fail',
		tgNotSupportCfgRestore:'MTG do not support config backup and restore',
		setSucc_2:'Set success,device will backup cfg',
		plSelDevOfSameType:'Please select device of same type',
		plSelDevOfSameVendor:'Please select device of same vendor',
		someDevDisableUpgrade:'Some devices disable uprade',
		someDevIsUpgrading:'Some devices are upgrading',
		plSelTargetVer:'Please select target version',
		upgradingWait:'Upgrading,please wait',
		upgradeSucc:'Set Success',
		upgradeFail:'Set Fail',
		adminStatusCanNotBe:'Admin status can not be',
		upgradeType:'Upgrade type',
		forceUpOrDown:'Force Upgrade or Degrade',
		forceUpOrDown_1:'check when target version is less than or equal to current version',
		confirmPwd:'Confirm Password',
		publicType:'Public Type',
		portNo:'Port No',
		workStatus:'Work Status',
		priRegStatus:'Pri Reg Status',
		secRegStatus:'Sec Reg Status',
		callStatus:'Call Status',
		lastCallTime:'Last Call Time',
		lastCallFailReason:'Last Call Fail Reason',
		voltage:'Voltage',
		current:'Current',
		pcmLaw:'PCM Law',
		workTime:'Work Time',
		rstCnt:'Reset Cnt',
		channelNum:'Channel Cnt',
		channelFail:'Chanel Fail',
		rtpDelay:'Rtp Delay',
		maxRtpDelay:'Max Rtp Delay',
		rxPkt:'RxPkt',
		txPkt:'TxPkt',
		txByte:'TxByte',
		rxByte:'RxByte',
		frameMode:'Frame Mode',
		lineCode:'Line Code',
		haulMode:'Haul Mode',
		clockSrc:'Clock Src',
		slaveType:'Slave Type',
		slaveIp:'Slave Ip',
		slaveTgNo:'Slave Tg No',
		slaveE1Count:'Slave E1 Count',
		slaveStartNo:'Slave Start No',
		slaveE1No:'Slave E1 No',
		txFrame:'TxFrame',
		rxFrame:'RxFrame',
		txFail:'TxFail',
		rxFail:'RxFail',
		mode:'Mode',
		netIndi:'Network Indi',
		opc:'OPC',
		dpc:'DPC',
		link0Status:'Link0 Status',
		link0Slc:'Link0 Slc',
		link0Port:'Link0 Port',
		link0Ts:'Link0 Slot',
		link1Status:'Link1 Status',
		link1Slc:'Link1 Slc',
		link1Port:'Link1 Port',
		link1Ts:'Link1 Slot',
		switchSide:'Switch Side',
		alertIndi:'Alerting Indication',
		remoteAddr:'Remote Addr',
		remotePort:'Remote Port',
		regFlag:'Register Flag',
		callMode:'Call Mode',
		supportSipT:'Support Sipt',
		detectTrunk:'Detect Trunk',
		transProtocol:'Trans Protocol',
		sipVer:'Sip Version',
		sipAccount:'Sip Account',
		bindPstnGrp:'Bind PSTN Grp',
		expireTime:'Expire Time',
		curCallCnt:'Cur Call Cnt',
		maxCallCnt:'Max Call Cnt',
		protocol:'Protocol',
		cloudCenter:'Cloud Center',
		welcome:'Welcome',
		youShouldSelDomainOrType:'Please select domain or product id',
		canNotFindCache:'Can not find cache',
		plSelDevToApply:'Please select device to apply',
		productId:'Product ID',
		updateTime:'Update Time',
		found:'Found',
		lastPage:'Last Page',
		nextPage:'Next Page',
		orderStatus_0:'WAIT_PAY',
// orderStatus_1:'PAID_NOT_CONFIRM',
// orderStatus_2:'PAID_AND_CONFIRMED',
		orderStatus_1:'PAID',
		orderStatus_2:'PAID',
		orderStatus_3:'CANCELED',
		orderStatus_4:'DELETED',
		orderStatus_5:'EXPIRED',
		licStatus_0:'NOT_SET',
		licStatus_1:'UPDATE_SUCC',
		licStatus_2:'UPDATE_FAIL',
		licStatus_3:'UPDATING',
		licStatus_4:'UPDATE_TIMEOUT',
		licStatus_5:'WAIT_UPDATE',
		lockStatus_0:'UNKNOWN',
		lockStatus_1:'LOCKED',
		lockStatus_2:'UNLOCKED',
		priceType_0:'BY DAY',
		priceType_1:'BY MONTH',
		back:'Back',
		cancelSucc:'Cancel Success',
		cancelFail:'Cancel Fail',
		cancelUpgrade:'Cancel Upgrade',
		apiInfo:'API Info',
		apiEnabled:'API Enable',
		maxReqPerMin:'Max Req Cnt Per Min',
		apiTrapFlag:'API Push',
		refreshFail:'Rfresh Fail',
		lastUsedTime:'Last Used Time',
		clientPort:'Client Port',
		clientIp:'Client IP',
		authFailCnt:'Auth Fail Cnt',
		totalReqCnt:'Total Req Cnt',
		totalPushCnt:'Total Push Cnt',
		reqCntPerMin:'Req Cnt Per Min',
		lastReqSn:'Last Req SN',
		canNotFindData:'Can not find data',
		exportingWait:'Exporting please wait...',
		userType:'User Type',
		pushAddr:'Push Addr',
		oldPwdCanNotEmpty:'Old password can not be empty',
		newPwdCanNotEmpty:'New password can not be empty',
		confirmPwdCanNotEmpty:'Confirm password can not be empty',
		newPwdConfirmPwdNotSame:'New password is not same with confirm password',
		oldPwdNotRight:'Old password is not right',
		oldPwd:'Old Password',
		newPwd:'New Password',
		server:'Server',
		addFlag:'Add Flag',
		outterIp:'Outer IP',
		cdrEndCode:'End Code',
		payload_0:"PCMU", 
		payload_4:"G.723.1",
		payload_8:"PCMA",
		payload_18:"G.729AB",
		payload_97:"iLBC-13K",
		payload_98:"iLBC-15K",
		payload_99:"AMR",
		payload_100:"AMR-GSM",
		payload_104:"T.38",
		payload_111:"G.726-16",
		payload_110:"G.726-24",
		payload_109:"G.726-32",
		payload_108:"G.726-40",
		cdrEndReason:'End Reason',
		cdrEndCode_0:"100_Trying",
		cdrEndCode_1:"101_Dialog_establishement",
		cdrEndCode_2:"180_Ringing",
		cdrEndCode_3:"181_Call_is_being_forwarded",
		cdrEndCode_4:"182_Queued",
		cdrEndCode_5:"183_Session_progress",
		cdrEndCode_6:"200_OK",
		cdrEndCode_7:"202_Accepted",
		cdrEndCode_8:"300_Multiple_choices",
		cdrEndCode_9:"301_Moved_permanently",
		cdrEndCode_10:"302_Moved_temporarily",
		cdrEndCode_11:"305_Use_proxy",
		cdrEndCode_12:"380_Alternative_service",
		cdrEndCode_13:"400_Bad_request",
		cdrEndCode_14:"401_Unauthorized",
		cdrEndCode_15:"402_Payment_required",
		cdrEndCode_16:"403_Forbidden",
		cdrEndCode_17:"404_Not_found",
		cdrEndCode_18:"405_Method_not_allowed",
		cdrEndCode_19:"406_Not_acceptable",
		cdrEndCode_20:"407_Proxy_auth_required",
		cdrEndCode_21:"408_Request_timeout",
		cdrEndCode_22:"409_Conflict",
		cdrEndCode_23:"410_Gone",
		cdrEndCode_24:"411_Length_required",
		cdrEndCode_25:"412_Precondition_failed",
		cdrEndCode_26:"413_Request_too_large",
		cdrEndCode_27:"414_Request_uri_too_long",
		cdrEndCode_28:"415_Unsupported_media",
		cdrEndCode_29:"416_Unsupported_uri",
		cdrEndCode_30:"420_Bad_extension",
		cdrEndCode_31:"421_Extension_required",
		cdrEndCode_32:"422_Session_timer",
		cdrEndCode_33:"423_Interval_too_brief",
		cdrEndCode_34:"480_Temporarily_unavailable",
		cdrEndCode_35:"481_No_transaction",
		cdrEndCode_36:"482_Loop_detected",
		cdrEndCode_37:"483_Too_many_hops",
		cdrEndCode_38:"484_Address_incomplete",
		cdrEndCode_39:"485_Ambiguous",
		cdrEndCode_40:"486_Busy_here",
		cdrEndCode_41:"487_Request_terminated",
		cdrEndCode_42:"488_Not_acceptable",
		cdrEndCode_43:"489_Bad_event",
		cdrEndCode_44:"490_Request_updated",
		cdrEndCode_45:"491_Request_pending",
		cdrEndCode_46:"493_Undecipherable",
		cdrEndCode_47:"494_Secagree_required",
		cdrEndCode_48:"500_Internal_server_error",
		cdrEndCode_49:"501_Not_implemented",
		cdrEndCode_50:"502_Bad_gateway",
		cdrEndCode_51:"503_Service_unavailable",
		cdrEndCode_52:"504_Gateway_time_out",
		cdrEndCode_53:"505_Version_not_supported",
		cdrEndCode_54:"513_Message_too_large",
		cdrEndCode_55:"580_Precondition",
		cdrEndCode_56:"600_Busy_everywhere",
		cdrEndCode_57:"603_Decline",
		cdrEndCode_58:"604_Does_not_exist_anywhere",
		cdrEndCode_59:"606_Not_acceptable",
		cdrEndCode_60:"687_Dialog_terminated",		
		cdrEndReason_0:"Dial Error",
		cdrEndReason_1:"Ring Timeout",
		cdrEndReason_2:"Onhook",
		cdrEndReason_3:"IP Conflict",
		cdrEndReason_4:"Routing Fail",
		cdrEndReason_5:"Dial Timeout",
		cdrEndReason_6:"Answer Timeout",
		cdrEndReason_7:"Pickup Fail",
		cdrEndReason_8:"INVITE Error",
		cdrEndReason_9:"Call Forward",
		cdrEndReason_10:"Rejected",
		cdrEndReason_11:"Offhold",
		cdrEndReason_12:"Recv BYE",
		cdrEndReason_13:"Send BYE",
		cdrEndReason_14:"CANCEL",
		cdrEndReason_15:"Not Found",
		cdrEndReason_16:"Busy Here",
		cdrEndReason_17:"Internal Error",
		portAlias:'Port Alias',
		peerAddr:'Peer Addr',
		peerIp:'Remote IP',
		localAddr:'Local Addr',
		callDuration:'Call Duration',
		payload:'Payload',
		sessionStatus:'Session Status',
		sendPkt:'Send Pkt',
		recvPkt:'Recv Pkt',
		sendByte:'Send Byte',
		recvByte:'Recv Byte',
		lostPkt:'Lost Pkt',
		jitterCnt:'Jitter',
		priSip:'Primary Sip',
		secSip:'Second Sip',
		port:'Port',
		curCallCnt:'Cur Call Count',
		totalCallCnt:'Total Call Count',
		totalCallFail:'Total Call Fail Count',
		na:'NA',
		noChange:'No Change',
		realAddr:'Real Addr',
		listChartChange:'Change view between table or chart',
		changeView:'Change View',
		generateTime:'Generate Time',
		totalCallMin:'Call Min',
		totalSucc:'Call Succ',
		recvTimeout:'Recv Timeout',
		sendLoss:'Send Loss',
		recvLoss:'Recv Loss',
		sendTimeout:'Send Timeout',
		minPingDelay:'Min Ping',
		operator:'Operator',
		riseCallCnt:'Rise Call Cnt',
		riseCallTime:'Rise Call Time',
		totalCallFailCnt:'Total Call Fail Cnt',
		riseCallFailCnt:'Rise Call Fail Cnt',
		sessionStatus_0:'abnormal',
		sessionStatus_1:'normal',
		sessionStatus_2:'single-pass',
		sessionStatus_3:'double-no-pass',
		startTime:'Start Time',
		endTime:'End Time',
		answerTime:'Answer Time',
		notSet:'Not Set',
		viewDev:'View Device',
		callDirection_0:'Call Out',
		callDirection_1:'Call In',
		userLog:'Operation Log',
		objectType_1:'DWG',
		objectType_2:'AG',
		objectType_3:'SIMBANK',
		objectType_4:'TG',
		objectType_5:'RULE',
		objectType_6:'ZONE',
		objectType_7:'SITE',
		objectType_8:'BKP',
		objectType_9:'GWP',
		objectType_10:'SIM',
		objectType_11:'GROUP',
		objectType_12:'DOMAIN',
		objectType_13:'POLICY',
		objectType_14:'NODE',
		objectType_15:'SYSTEM',
		objectType_16:'PROCESS',
		objectType_17:'PORT',
		objectType_18:'SMS',
		objectType_19:'USSD',
		objectType_20:'CDR',
		objectType_21:'PAIDGROUP',
		objectType_22:'ALARM',
		objectType_23:'PAIDCARD',
		objectType_24:'NODEGROUP',
		objectType_25:'CLOUD',
		objectType_26:'USER',
		objectType_27:'NODELIST',
		objectType_28:'VERSION',
		objectType_29:'SERVER_LICENSE',
		objectType_30:'DOMAIN_LICENSE',
		objectType_31:'RECHARGE_CARD',
		objectType_32:'STATIC_NUMBER',
		objectType_33:'DYNAMIC_NUMBER',
		objectType_40:'DEV_CFG_MODEL',
		objectType_41:'DEV',
		objectType_42:'AUTH_NUMBER',
		objectType_43:'FREQ_NUMBER',
		objectType_44:'SIP Server',
		objectType_45:'ALARM_MAN',
		objectType_46:'ALARM_GRP',
		objectType_47:'ALARM_RELATIONSHIP',
		objectType_48:'ALARM_PUSH_LEVEL',
		objectType_49:'DEVICE_CFG',
		operateType_1:'ADD',
		operateType_2:'DELETE',
		operateType_3:'UPDATE',
		operateType_4:'UPGRADE',
		operateType_5:'REBOOT',
		operateType_6:'RESET',
		operateType_7:'RESTORE',
		operateType_8:'ELEGANT',
		operateType_9:'IMPORT',
		operateType_10:'START_SYSLOG',
		operateType_11:'STOP_SYSLOG',
		operateType_12:'LOGIN',
		operateType_13:'LOGOUT',
		operateType_14:'RECHARGE',
		operateType_15:'RENEW',
		operateType_16:'REMOTE_WEB',
		operateType_21:'CANCEL_UPGRADE',
		operateType_22:'CLEAN_ALL',
		operateType_23:'APPLY',
		operateType_30:'RESTORE_CFG',
		operateType_31:'BACKUP_CFG',
		operateType_32:'SET_DBO',
		ipAddr:'IP Address',
		operate:'Operate',
		objectType:'Object Type',
		objectName:'Object Name',
		objectDomain:'Object Domain',
		userDomain:'User Domain',
		detailView:'Detail View',
		frameErr:'Frame Error',
		codeErr:'Code Error',
		crcErr:'Crc Error',
		ebitErr:'EbitErr',
		workTime:'Work Time',
		sendFrame:'Send Frame',
		recvFrame:'Recv Frame',
		sendFail:'Send Fail',
		recvFail:'Recv Fail',
		msgRetries:'Send Dup Msg',
		recvDupMsg:'Recv Dup Msg',
		delayErr:'Rtp Delay',
		lostCnt:'Lost Cnt',
		jitterErr:'JitterErr',
		rtpErr:'RtpErr',
		rstCnt:'RST Cnt',
		ip2PstnCall:'Ip2PstnCall',
		pstn2IpCall:'Pstn2IpCall',
		ip2PstnFail:'Ip2PstnFail',
		pstn2IpFail:'Pstn2IpFail',
		totalOutCallCnt:'Total Out Call',
		totalOutFailCall:'Total Out Fail Call',
		totalInCallCnt:'Total In Call',
		totalInFailCall:'Total In Fail Call',
		portCalc:'Port Stat',
		calcList:'Stat List',
		searchCondition:'Search Condition',
		searchResult:'Search Result',
		search:'Search',
		today:'Today',
		last3Day:'3 Day',
		last7Day:'7 Day',
		plSelOperateType:'Select Operate',
		plSelOperateObject:'Select Object',
		searchDetail:'Search Detail',
		userName:'User Name',
		domainList:'Domain List',
		dcSwitch:'DC Switch',
		alarmMan:'Alarm Contacts',
		alarmGrp:'Alarm Group',
		addMan:'Add Contact Man',
		addToGrp:'Add to Contact Group',
		addAlarmGrp:'Add Contact Group',
		pushToGrp:'Push to Alarm Grp',
		ruleType:'Rule Type',
		ruleDesc:'Rule Desc',
		ruleCondition:'Rule Condition',
		ruleCondition_1:'>=',
		ruleCondition_2:'>',
		ruleCondition_3:'<',
		ruleCondition_4:'<=',
		ruleCondition_5:'=',
		ruleCondition_6:'!=',
		ruleType_1:'Alarm Level',
		ruleType_2:'Alarm Type',
		ruleType_3:'Alarm Desc',
		ruleType_4:'Total Alarm',
		ruleType_5:'Device Type',
		pushType:'Push Type',
		pushObject:'Push Object',
		alarmPushRule:'Alarm Push Rule',
		pushType_1:'Alarm Contacts',
		pushType_2:'Alarm Group',
		singleAlarm:'Single Alarm',
		alarmDesc:'Alarm Desc',
		timeCheckMax:'Filter Cycle',
		alarmId:'Alarm ID',
		alarmManResp:'Responsible Man',
		plSelAlarmManResp:'Please select responsible man',
		plSelAlarmMan:'Please select alarm contacts',
		alarmHis:'Alarm History',
		defaultConfModel:'File Type',
		defaultFile:'Deafult File',
		normalFile:'Normal File',
		drpRemoteTel:'DRP Remote Telnet',
		rmRunStatus:'DRP Status',
		rmLastRegTime:'DRP Reg Time',
		notDevAlarm:'It is not device alarm,can not view device info',
		alarmType_1:"ALARM",
		alarmType_2:"EVENT",
		alarmType_3:"REPAIR",
		alarmAlarmType_0:"Default",
		alarmAlarmType_1:"Server",
		alarmAlarmType_2:"Device",
		alarmAlarmType_3:"Call",
		alarmAlarmType_4:"Service",
		cleanFlag_0:"CLEAN_NULL",
		cleanFlag_1:"CLEAN_DEV",
		cleanFlag_2:"CLEAN_SRV",
		alarmType:'Alarm Type',
		nameCanNotEmpty:'Name can not be empty',
		ruleTypeHelp:'Info:the rule will not be added if it was in table',
		alarmGrpHelp_0:'Info:the alarm contact will be set to the CC people',
		alarmGrpHelp_1:'Info:responsible person will be set to the mail recipient',
		filterTextClear:'show all',
		filterPlaceHolder:'Filter',
		infoTextEmpty:'Empty list',
		infoText:'Showing all {0}',
		infoTextFiltered:'<span class="label label-warning">Filtered</span> {0} from {1}',
		removeAllLabel:'Remove all',
		removeSelectedLabel:'Remove selected',
		moveSelectedLabel:'Move selected',
		moveAllLabel:'Move all',
		notSel:'Not Selected',
		mtgSwitch:'Mtg Switch',
		mtgThresholdSec:'Threshold',
		mtgOfflineCallTimeSec:'Offline Call Time',
		mtgCallTimeSec:'Call Time',
		mtgStatus:'Lock Status',
		curPstn:'PSTN Calls',
		curSip:'SIP Calls',
		capsIn:'Call In Caps',
		capsOut:'Call Out Caps',
		hour:'hour',
		riseCallCntDesc:'new call count in sampling time，eg 5m/15m',
		riseCallTimeDesc:'new call time in sampling time',
		acdDesc:'average call time in sampling time',
		asrDesc:'average call success rate in sampling time',
		capsInDesc:'new call in count per sec',
		capsOutDesc:'new call out count per sec',
		curCallCntDesc:'call count per sec',
		curPstnDesc:'pstn call count per sec',
		curSipDesc:'sip call count per sec',
		runTimeAfterRegDesc:'run time after device register,calc by server',
		neRunTimeDesc:'Run time report by device',
		curCpuUsageDesc:'Device cpu usage this moment',
		devMemUsageDesc:'Device mem usage this moment',
		commFailCountDesc:'Commnication fail count in minitus',
		pingSipDelayDesc:'Delay of ping device sip server',
		pingSipLostDesc:'The lost rate of ping device sip server',
		curPingDelayDesc:'Delay of ping device',
		maxPingDelayDesc:'Max delay of ping device',
		recvLostRateDesc:'Lost rate when server recvice device package',
		sendLostRateDesc:'Lost rate when server send package to device',
		devMemUsage:'Device Mem Usage',
		commFailCount:'Comm Fail Count',
		pingSipDelay:'Ping Sip Server Delay',
		pingSipLost:'Ping Sip Server Lost',
		objectDesc:'Object Desc',
		devAllAlarm:'Device All Alarm',
		reportTime:'Report Time',
		cleanTime:'Clean Time',
		timeZone:'Time Zone',
		capsThreshold:'Caps Threshold',
		asrThreshold:'Asr Threshold',
		confirmFlag_0:'NOT CONFIRM',
		confirmFlag_1:'CONFIRMED',
		confirmFlag:'Confirm Flag',
		confirmAlarmHelp:'The alarm will not be pushed and no remind after confirm',
		alarmObject:'Alarm Object',
		cleanCdr:'cleanCdr',
		sureToClean:'sureToClean',
		cleanSucc:'cleanSuccess',
		cleanFail:'cleanFail',
		MessageDescription:'Message',
		contentText:'Content',
		writeMessage:'Write Message',
		receivedMessage:'Received Message',
		sentmessage:'Sent Message',
		draftBox:'draftBox',
		validCode:'Valid Code',
		notClearPlClick:'Not clear please click',
		changeAnother:'Change One',
		total:'total',
		unread:'unread',
		read:'read',
		sendToRole:'Recipients',
		roleId:'roleId',
		youNotChoiseRole:'Please select recipients',
		youNotWriteTheme:'Please input theme',
		theme:'Theme',
		detailedInformation:'Detail Info',
		writeAgain:'Edit Again',
		addresser:'Addresser',
		send:'send',
		repeal:'repeal',
		stateDescription:'Status',
		cancelSucc1:'Cancel Success',
		cancelFail1:'Cancel Fail',
		cancelMessage:'Cancle Message',
		cancelSome:'Cancel Some',
		recede:'Rescinded',
		cancelMail:'Rescinded',
		youNotWriteContent:'Please input content',
		sendSuccess:'Send Success',
		saveSuccess:'Save Success',
		resetReason:'Reset Reason',
	    devResetReason_1:"POWER_OFF",     
	    devResetReason_2:"INIT_INET_FAIL",
	    devResetReason_3:"CLI_SET_WORKMODE",
	    devResetReason_4:"CLI_SET_MENU_CFG",
	    devResetReason_5:"SET_DSP_CFG",
	    devResetReason_6:"CLI_RESET",
	    devResetReason_7:"CLOUD_RESTORE_CFG",
	    devResetReason_8:"PROVISION_DELAY_RESET",
	    devResetReason_9:"PROVISION_RESET",
	    devResetReason_10:"DAILY_REBOOT",
	    devResetReason_11:"WEB_REBOOT",
	    devResetReason_12:"SNMP_REBOOT",
	    devResetReason_13:"BEIJING_TELECOM_REBOOT",
	    devResetReason_14:"CLOUD_SET_REBOOT",
	    devResetReason_15:"FEATURE_CODE_REBOOT",
	    devResetReason_16:"NOTIFY_CHECK_SYNC",
	    devResetReason_17:"SEGMENT_FAULT",
	    devResetReason_18:"SYSTEM_START_FAIL",
	    devResetReason_19:"TR069_REBOOT",
	    devResetReason_20:"DSP_NO_RESPONSE",
	    devResetReason_21:"WATCHDOG",
	    devResetReason_22:"UNKNOWN",
		callSwitch:'Call Alarm Switch',
		asrThresholdHelp:'Server will create alarm if asr is less than this value',
		capsThresholdHelp:'Server will create alarm if caps is less than this value',
		preMoney:'Money',
		preRate:'Rate',
		backSmall:'Back to small chart',
		viewBig:'View big chart',
		sureToDelSite:'If having some devices,it is very slow to move devices to the default site by the server,sure to delete',
		cent:'cent',
		nonnegativeNumValid:'Input must be nonnegative number',
		rateNumValid:'Input must between 0-100',
		positiveNumValid:'Input must be positive number',
		normalNameValid:'Input length must between 2-31',
		productNameValid:'Input must be 0-9,a-z,A-Z,or _',
		priceValid:'Input must be positive real number,and decimal length must between 1-2',
		chinaMobileValid:'Please input valid mobile number',
		emptyValid:'Can not be empty',
		yourMessageIsSent:'Your message is sent',
		thisMessageIsSentSuccessfullyAndIsSavedToTheSentMessage:'This message is sent successfully,and is saved to the Sent Message',
		writeAnotherMessage:'Write Another Message ',
		viewThisMessage:'View This Message',
		configuration:'configuration',
		selectAll:'Select All',
		noSelect:'noSelect',
		serviceVersion:'Service Version',
		versionList:'Version List',
		relyVer:'Rely Ver',
		packageVer:'Package Ver',
		status:'status',
		official:'official',
		test:'test',
		detailedDescription:'Detail',
		synVersion:'Sync Version',
		notExp:'Only one can be exported at a time.',
		sureToExp:'Sure to export',
		expFaile:'expFaile',
		sureToSyn:'Synchronous version may be a few minutes Please make sure ...',
        message:'message',
        pleaseWaitAMoment:'Please Wait A Moment ...',
        submitSuccess:'Submit Success',
        submitFail:'Submit Faile',
        success:'success',
        fail:'fail',
        versionMessage:'Version Message',
        submit:'submit',
        edit:'edit',
        backOut:'backOut',
        producers:'producers',
        plSelVersion:'All Version',
        relyVerVersionFaile:'relyVerVersionFaile',
        sysnSucess:'Sycn Success',
        sysnFail:'Sycn Fail',
        selectFile:'Select File',
        sureUploadFile:'Upload Version',
        uploadFile:'Upload File...',
        uploadSuccess:'Upload Success',
        uploadFail:'Upload Fail',
        notLegal:'No permissions',
        plSelFile:'Please select version',
        plSelDomain:'Please select domain',
        domainHelp:'Set the visiblity of domain when device upgrade',
        versionBlackAndwhileList:'Visiable domain',
        visible:'Visible',
        disVisible:'Invisible',
        unifiedCommunications:'Unified Communications',
        selectAllSet:'Select All',
        fileFormatGzOrZip:'Version should be end with gz or zip',
        setWait:'Setting please wait a few minutes',
        tooLongTheme:'Subject is too long, will be limited to 126 characters',
        tooLongContent:'The text is too long, the text will be limited to 4095 characters',
        saveFail:'Save fail',
        cancelWait:'Please wait a moment is cancelled',
        chooseRole:'Choose a role',
        detailDescNotNull:'Description cannot be empty',
        commonReport:'Common report',
        userReport:'User report',
        alarmReport:'Alarm report',
        domainNum:'Several new domain',
        userNum:'New users',
        plSelPri:'Please select privilege',
        loginUserNum:'User login number',
        localSysNum:'Local server number',
        devNum:'New device',
        devRegisterNum:'Device registration number',
        drpRegisterNum:'Drp register number',
        devDeteleNum:'Device delete number',
        devRebootNum:'Device Reboot number',
        alarm:'Alarm number',
        seriousAlarmNum:'Serious alarm number',
        repairAlarmNum:'Repair alarm number',
        pushAlarmNum:'Push alarm number',
        domainNumDesc:'Use the time to add the number of domains, daily 23:00 statistics',
        userNumDesc:'The number of new users of the sampling time, daily 23:00 statistics',
        loginUserNumDesc:'Sample time to log in the number of users, daily 23:00 statistics',
        localSysNumDesc:'Sampling time of the local server, daily 23:00 statistics',
        devNumDesc:'Sampling time of new equipment, daily 23:00 statistics',
		devRegisterNumDesc:'Sampling time on the number of registered devices, daily 23:00 statistics',
		drpRegisterNumDesc:'Sampling time on the number of drp registered devices, daily 23:00 statistics',
		devDeteleNumDesc:'Number of device delete sampling time, daily 23:00 statistics',
		devRebootNumDesc:'The number of device restart sampling time, daily 23:00 statistics',
		alarmNumDesc:'Sampling time of the alarm number, daily 23:00 statistics',
		seriousAlarmNumDesc:'Sampling time on the number of serious warning, daily 23:00 statistics',
		repairAlarmNumDesc:'Sampling time on the number of alarm  repair, daily 23:00 statistics',
		pushAlarmNumDesc:'Sampling time on the number of alarm push, daily 23:00 statistics',
		innerIpAddr:'Inner ip address',
		plSelSite:'Please select the site',
		siteHelp:'You must select a site',
		viewSite:'View site',
		addSite:'Add site',
		buttonList:'Button list',
		buttonName:'Button name',
		rtpJitterMean:'Average jitter',
		rtpJitterMax:'Max jitter',
		rtpLostRateMax:'Max loss rate',
		rtpLostRateMean:'Avg loss rate',
		rtpDelayMax:'Max delay',
		rtpDelayMean:'Avg delay',
		perView:'Privilege view',
		setGroud:'Set groud',
		oldSite:'Old site',
		deviceConfig:'Device configuration',
		sipServer:'Sip server',
		netMangerConfig:'Net manger config',
		drpConfig:'Drp config',
		selConfig:'Select config',
		drpAddress:'Drp address',
		drpPort:'Drp port',
		sipAddress:'Sip address',
		sipPort:'Sip port',
		netAddress:'Net manger address',
		netPort:'net manger port',
		drpSwitch:'Drp switch',
		sipSwitch:'Sip switch',
		netMangerSwitch:'Net manger Switch',
		netConfig:'Net config',
		netSwitch:'Net Switch',
		ipProtocol:'Ip protocol',
		networkMode:'Network mode',
		routing:'routing',
		bridge:'bridge',
		networkSet:'Network set',
		wanPort:'WAN port',
		autoIp:'Auto get ip',
		manuaIp:'Manually get IP',
		wanMask:'Subnet mask',
		wanGateway:'The default gateway',
		pppUsername:'PPPOE username',
		pppPassword:'PPPOE password',
		pppServiceName:'PPPOE service name',
		wanMtu:'WAN mtu',
		lanPort:'LAN port',
        lanMtu:'LAN mtu',
        dnsServer:'DNS server',
        manuaDNS:'Manua get DNS',
        autoDNS:'Auto get DNS',
        secDNS:'Secondary DNS',
        sipAddrOrport:'SIP port or address can not be empty',
        netAddrOrport:'Net manger port or address can not be empty',
        drpAddrOrport:'DRP port or address can not be empty',
        wanMtuIsNull:'WAN mtu is null',
        IPOrDNSIsNull:'IP or DNS is null',
        wanMtuRand:'WAN mtu 512~1500',
        lanMtuRand:'LAN mtu 512~1500',
        pppOEIsNull:'PPPOE is null',
        selSameDoamin:'Choose equipment of the same domain',
        devConfig:'Equipment config',
        oldConfig:'Old config',
        newConfig:'new Config',
        wanIp:'WAN IP',
        lanMask:'LAN subnet mask',
        preConfig:'Predefined configuration',
        sipPortConf:'SIP port config',
        addBatch:'Batch increase',
        disablePort:'Disabled port',
        register:'register',
        mainSipName:'Main SIP name',
        mainSipAccount:'Main SIP account',
        mainSipAuthAccount:'Main SIP authentication account',
        mainAatuPassword:' Main authentication password',  
        sipName:'SIP name',
        sipAccount:'SIP account',
        sipAuthAccount:'SIP authentication account',
        authPassword:'authentication password',
        dialNum:'With dial number',
        delayTime:'Delay time(second)',
        notDisturb:'Not disturb',
        callId:'Call id',
        callWaitTone:'Call wait tone',
        callWait:'Call wait',
        unCall:'Unconditional call',
        busyCall:'Busy call transfer',
        cfnry:'CFNRy',
        step:'step',
        samePossword:'All port same possword',
        workMode:'Work mode',
        voiceAndFax:'Voice and fax',
        voice:'voice',
        fax:'fax',
        pos:'POS',
        playCallWaitTone:'Play call wait tone',
        stratMainSipAccount:'Start main SIP account',
        stratSipAccount:'Start SIP account',
        startPort:'Start port',
        endPort:'End port',
		errorTip:'One of the main SIP account or on behalf of the dial must be configured',
	    delayTimeRand:'Delay time must be 0-10',
	    mainSipAccountLessThan32:'Main sip account by Numbers, letters, characters (except English \' \ ") and less than 32 bit',
	    mainSipAuthAccountLessThan64:'Main sip auth account by Numbers, letters, characters (except English \' \ ") and less than 64 bit',
	    mainSipNameLessThan32:'Main sip name by Numbers, letters, characters (except English \' \ ") and less than 32 bit', 
	    sipAccountLessThan32:'Sip account by Numbers, letters, characters (except English \' \ ") and less than 32 bit',
	    sipAuthAccountLessThan64:'Sip auth account by Numbers, letters, characters (except English \' \ ") and less than 64 bit',
	    sipNameLessThan32:'Sip name by Numbers, letters, characters (except English \' \ ") and less than 32 bit', 
	    unCallLessThan32:'Unconditional call by Numbers, letters, characters (except English \' \ ") and the length is less than 32.',
	    busyCallLessThan32:'Busy call transfer by Numbers, letters, characters (except English \' \ ") and the length is less than 32.',
	    cfnryLessThan32:'CFNRy by Numbers, letters, characters (except English \' \ ") and the length is less than 32.',
	    unCallNotSame:'Unconditional call not same main sip account',
	   busyCallNotSame:'Busy call transfer not same main sip account',
	   cfnryNotSame:'CFNRy not same main sip account',
	   endPortLessThanstratPort:'End port less than strat port',
	   isDigital:'last 3 bit must be digital',
	   stepRand:'Step rand 0-100000',
	   callFun:'Call the function keys',
	   webPort:'webPort',
	   callSwitch:'Call function switch',
	   callKeep:'The call to keep',
	   webPort:'WEB port',
	   webSwitch:'WEB switch',
	   sslPort:'SSL port',
	   webPortRand:'WEB port scope 1024-65535 or 80',
	   sslPortRand:'SSL port scope 1024-65535 or 443',
	   callKeepRand:'* beginning end # # middle can fill in the 0 to 2 digits',
	   netIpError:'The network management IP address error',
	   netPortError:'The network management port between 0-65535',
	   sipIpError:'SIP IP address error',
	   sipPortError:'SIP port between 0-65535',
	   drpIpError:'DRP IP address error',
	   drpPortError:'DRP port between 0-65535',
	   secDNSError:'Secondary  DNS error',
	   mainDNSError:'main DNS error',
	   netWorkIpError:'Network IP address error',
	   wanMaskError:'WAN mask error',
	   wanGatewayError:'WAN gate way error',
	   lanIpAddrValue:'LAN IP address error',
	   lanWanMaskError:'LAN mask ip error',
	   jitterSec: 'Jitter filter',
	   cleanConfig:'Clean config',
	   notSame:'Port not same',
	   mainAatuPasswordRand:'Main Auth password  by Numbers, letters, characters (except English \' \ ")',
	   dialNumRand:'Dial number by Numbers, letters, characters (except English \' \ ")',
	   restartEffect:'Tip: the SSL port and web port configuration will take effect after the device is reset',
	   sipTip:'Tip: if you want to configure the SIP port, please click the S icon in the list of operations.',
	   netTip:'Tip: network configuration will take effect after the restart of the device.',
	   pppOEIsError:'PPPOE error it not china',
	   exitmainSip:'Main account already exists',
	   isDigital1:'Main accuount last 3bit not big 1000',
	   portTip:'If the delay time in the dial, on behalf of the dial number will not take effect',
	   drpStatus:'DRP status',
	   unregistered:'Unregistered',
	   block:'Block',
	   needAuth:'NEED_AUTH',
	   ipHistory:'IP history',
	   setColumns:'Columns config',
	   passWordRand:'The password is composed of a number of letters and English characters and more than six bits is less than sixteen bits.',
	   timeFormatError:'Time format errror ,2015-02-02',
	   validationIsNull:'Verification code cannot be empty',
       validationError:'Verification code is not correct',
       sysCustom:'System defined',
       userDefined:'User defined',
       importFormat:'Import format',
       

	};
});


