Ext.define('app.store.license.LicSrvModel', {
        extend: 'Ext.data.Model',
        fields: [
            {name:'uuid',type:'int'},
            {name:'specSysUuid',type:'int'},
            {name:'alias',type:'string'},
            {name:'srvUuid',type:'string'},
            {name:'srvDomain',type:'string'},
            {name:'serialNo',type:'int'},
            {name:'signType',type:'int'},
            {name:'version',type:'string'},
            {name:'srvMode',type:'int'},
            {name:'srvMagic',type:'string'},
            {name:'maxSimCard',type:'int'},
            {name:'serviceApi',type:'int'},
            {name:'hbmFeatures',type:'int'},
            {name:'hbmFeatures02',type:'int'},
            {name:'hbmFeatures03',type:'int'},
            {name:'validDays',type:'int'},
            {name:'expiredDate',type:'date'},
            {name:'signDate',type:'date'},
            {name:'signAuthor',type:'string'},
            {name:'dnsUrl',type:'string'},
            {name:'dnsUrl02',type:'string'},
            {name:'authInfo',type:'string'},
            {name:'licStatus',type:'int'},
            {name:'leftDays',type:'int'},
            {name:'totalSimCard',type:'int'},
            {name:'detailDesc',type:'string'},
            {name:'status',type:'int'},
        	/* system info*/
            {name:'sysUuid',type:'int'},
            {name:'sysName',type:'string'},
            {name:'sysAlias',type:'string'},
            {name:'adminStatus',type:'int'},
            {name:'oprStatus',type:'int'},
            {name:'runStatus',type:'int'},
            {name:'sysDetailDesc',type:'string'},
            {name:'totalNeCount',type:'int'},
            {name:'sysTotalSimCard',type:'int'},
            {name:'trialBalance',type:'float'},
            {name:'premiumBalance',type:'float'},
            {name: 'licFirstCost',type: 'int'},
	        {name: 'licPeriodCost',type: 'int'},
        ]
});